export const ALL_PRODUCT_REQUEST='REQUEST_ALL_PRODUCT'
export const ALL_PRODUCT_SUCCESS='ALL_PRODUCT_SUCCESS'
export const ALL_PRODUCT_FAIL='ALL_PRODUCT_FAIL'

export const CLEAR_ERRORS='CLEAR_ERRORS'

export const PRODUCT_DETAILS_REQUEST='REQUEST_PRODUCT_DETAILS'
export const PRODUCT_DETAILS_SUCCESS='PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL='PRODUCT_DETAILS_FAIL'

