export const ALL_PRODUCT_REQUEST='REQUEST_ALL_PRODUCT'
export const ALL_PRODUCT_SUCCESS='ALL_PRODUCT_SUCCESS'
export const ALL_PRODUCT_FAIL='ALL_PRODUCT_FAIL'

export const CLEAR_ERRORS='CLEAR_ERRORS'
